language: python
sudo: false
python: 3.5

cache:
  pip: true

git:
  depth: false

branches:
  except:
  - gh-pages

before_install:
- pip install --upgrade pip setuptools wheel

install:
- pip install https://github.com/opencobra/memote/archive/fix_memote_report_history.zip

script:
- ./scripts/travis_deploy.sh
